ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.RWAtrap]
path = "out/Trap.sol/Trap.json"
response_contract = "0xd22EaE6A80719D474659737c5C0F3eeB48Eb4517" # change your deploy contract from forge script
response_function = "mintRWA(string,string,string,string,string,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 1
private_trap = true
whitelist = []
address = 



